a=float(input('entre num1'))
b=float(input('entre num2'))
c=float(input('entre num3'))
d=float(input('entre num4'))
e=float(input('entre num5'))
f=float(input('entre mum6'))
g=float(input('entre num7'))
h=float(input('entre num8'))
i=float(input('entre num9'))
j=float(input('entre num10'))
miangin=(a+b+c+d+e+f+g+h+i+j)/10
print(miangin)